
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  #配置数据源
  datasource:
  ############################## 本地 ###########################################
#    url: jdbc:mysql://localhost:3306/OnlyDream?useUnicode=true&characterEncoding=UTF-8
#    username: OnlyDream
#    password: 123456
############################## 阿里云 ###########################################
#    url: jdbc:mysql://47.106.66.45:3306/tjcx?useUnicode=true&characterEncoding=UTF-8
#    username: OnlyDream
#    password: 123456
############################## 腾讯云 ###########################################
    url: jdbc:mysql://122.152.234.74:3306/OnlyDream?useUnicode=true&characterEncoding=UTF-8
    username: OnlyDream
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    cache: true
    charset: UTF-8
    content-type: text/html
    suffix: .html

#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:mapper/*.xml
